
const SData = [
    {
        id: 1,
        product_anime: 'Naruto',
        img: "https://yt3.ggpht.com/a/AATXAJwx-_ZnZdDNMMZc8EhFdOsjcPkVIgj89NK8CQ=s900-c-k-c0xffffffff-no-rj-mo",
        title: "Uzumaki Naruto",
        desc: '',
        quantity: 0,
        price: 520,
    },
    {
        id: 2,
        product_anime: 'Naruto',
        img: "https://yt3.ggpht.com/a/AATXAJyatTImWtppjEVMV1n95VAgYL7KVvDTr7_QpA=s900-c-k-c0xffffffff-no-rj-mo",
        title: "Uchiha Sasuke",
        desc: '',
        quantity: 0,
        price: 300,
    },
    {
        id: 3,
        product_anime: 'Naruto',
        img: "https://yt3.ggpht.com/a/AATXAJzO8NPJi6DUfh074fZZEmLnMGdkqVh2s578sQ=s900-c-k-c0xffffffff-no-rj-mo",
        title: "Hatake Kakashi",
        desc: '',
        quantity: 0,
        price: 450,
    },
    {
        id: 4,
        product_anime: 'Naruto',
        img: "https://iv1.lisimg.com/image/4069701/600full-jiraiya.jpg",
        title: "Jiraya (Pervi Sage)",
        desc: '',
        quantity: 0,
        price: 500,
    },
    {
        id: 5,
        product_anime: 'Naruto',
        img: "https://fsb.zobj.net/crop.php?r=RQhLZb0TiK2-OH5o-CreyX-rh8p4c2cIV_BUxWqjerOuJQp3-Z-_mRlIZAucgetAZgpjAkCcw1cJqZvmkh-l5hZ_LWCeNYwiQwKKbeKwG6a6CnRejYDKMU77W7ImUAyEbvOTtc-NxlknWgtu",
        title: "Uchiha Madara",
        desc: '',
        quantity: 0,
        price: 1500,
    },
    {
        id: 6,
        product_anime: 'Naruto',
        img: "http://images5.fanpop.com/image/photos/30700000/itachi-akatsuki-naruto-shippuden-30746593-640-960.jpg",
        title: "Uchiha Itachi",
        desc: '',
        quantity: 0,
        price: 900,
    },
    {
        id: 7,
        product_anime: 'one-piece',
        img: "https://c4.wallpaperflare.com/wallpaper/119/612/15/one-piece-monkey-d-luffy-hat-anime-wallpaper-preview.jpg",
        title: "Monkey D. Luffy",
        desc: '',
        quantity: 0,
        price: 3000,
    },
    {
        id: 8,
        product_anime: 'one-piece',
        img: "https://c4.wallpaperflare.com/wallpaper/430/896/23/one-piece-roronoa-zoro-hd-wallpaper-preview.jpg",
        title: "Roronoa Zoro",
        desc: '',
        quantity: 0,
        price: 1111,
    },
    {
        id: 9,
        product_anime: 'one-piece',
        img: "https://i.pinimg.com/originals/23/5c/3f/235c3f04cf70c4266323a16426ba187c.jpg",
        title: "Vinsmoke Sanji",
        desc: '',
        quantity: 0,
        price: 1032,
    },
    {
        id: 10,
        product_anime: 'one-piece',
        img: "https://pm1.narvii.com/6692/a036740a5329decd5142f86d6a51d820b506b74e_hq.jpg",
        title: "Nami",
        desc: '',
        quantity: 0,
        price: 366,
    },
    {
        id: 11,
        product_anime: 'one-piece',
        img: "https://i.pinimg.com/originals/3a/d2/7e/3ad27e2b8e86855a61dfc2888a4518a8.jpg",
        title: "Uchiha Madara",
        desc: '',
        quantity: 0,
        price: 500,
    },
    {
        id: 12,
        product_anime: 'one-piece',
        img: "https://i.pinimg.com/564x/f6/bb/e7/f6bbe7307a4a41844c7e1fb3c4c4b123.jpg",
        title: "Nico Robin",
        desc: '',
        quantity: 0,
        price: 930,
    }
    
]

export default SData;